---

 - name: set preserve_hostname in /etc/cloud/cloud.cfg
   lineinfile: 
     dest: "/etc/cloud/cloud.cfg"
     line: "preserve_hostname: True"
     state: present
 
 - name: install libselinux-python packages (submit)
   yum: name=libselinux-python state=latest
#   when: submit_host == "yes"

# - name: install libselinux-python packages (compute)
#   yum: name=libselinux-python state=present
#   environment:
#     http_proxy: "http://{% for host in groups['submit_nodes'] %}{{hostvars['headnode']['ansible_host'] }}{% endfor %}:1375"
#   when: submit_host == "no"

 - name: set up /etc/hosts
   template: src=hosts.j2 dest=/etc/hosts

 - name: set up /etc/ssh/sshd_config
   template: src=sshd_config.j2 dest=/etc/ssh/sshd_config

 - name: restart sshd
   service: name=sshd state=restarted

 - name: set hostname
   hostname: name={{ inventory_hostname }}

# - name: configure yum proxy on compute nodes
#   lineinfile:
#     dest: "/etc/yum.conf"
#     insertafter: EOF
#     line: "{% for host in groups['submit_nodes'] %}proxy = http://{{ hostvars[host]['inventory_hostname'] }}:1375 
#            {% endfor %}"
#   when: submit_host == "no"

 - name: install common packages
   yum: name={{ item }} state=present
   with_items:
     - "vim" 
     - "rsync"
     - "epel-release"
     - "openmpi"       #torque
     - "openmpi-devel"       #torque
     - "gcc"           
     - "gcc-c++"       
     - "gcc-gfortran"  
     - "openssl-devel" 
     - "libxml2-devel" 
     - "boost-devel"   
     - "net-tools"
     - "strace"
     - "fail2ban"
     - "wget"  # needed for building QE
     - "readline-devel"  #req for slurm
     - "pam-devel"       # req for slurm
     - "perl-ExtUtils-MakeMaker" # req for slurm
     - "python-firewall"
     - "fftw" # req for QE... need a better way to specify these!!!

 - name: install stuff from epel
   yum: name={{ item }} state=latest
   with_items:
     - "python-pip"
     - "munge" # doesn't work with torque currently... even w/ --enable-munge-auth 
     - "munge-devel"
     - "munge-libs"

 - name: install pexpect from pip
   pip: name=pexpect version=3.3
   when: submit_host == "yes"

 - name: turn off requiretty for sudo
   lineinfile:
     dest: /etc/sudoers
     regexp: "Defaults    requiretty"
     line:  "Defaults    !requiretty"
     state: present

 - name: fix sudo path (for qterm, etc)
   lineinfile:
     dest: /etc/sudoers
     regexp: "Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin"
     line: "Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin"
     state: present

# - name: install tinyproxy
#   yum: name=tinyproxy state=present
#   when: submit_host == "yes"

 - name: export /home to compute nodes
   lineinfile:
     dest: /etc/exports
     line:  "/home 10.0.0.0/24(rw,no_root_squash)"
     state: present
   tags:
     - export_home
   when: submit_host == "yes"

 - name: allow all to write /N
   file: 
     path: /N/
     state: directory
     mode: 0777

 - name: export /N to compute nodes
   lineinfile:
     dest: /etc/exports
     line:  "/N 10.0.0.0/24(rw,no_root_squash)"
     state: present
   tags:
     - export_N
   when: submit_host == "yes"

 - name: allow use_nfs_home_dirs
   seboolean: name=use_nfs_home_dirs state=yes persistent=yes
   tags:
     - export_home
   when: submit_host == "no"

 - name: restart nfs
   service: name=nfs state=restarted
   when: (submit_host == "yes" and cleanup == "no")

# - name: restart nfs
#   service: name=nfs state=restarted
#   when: (submit_host == "yes" and cleanup == "yes")

 - name: import /home on compute nodes
   lineinfile:
     dest: /etc/fstab
     line:  "{{ headnode_private_ip }}:/home  /home  nfs  defaults 0 0"
     state: present
   tags:
     - export_home
   when: submit_host == "no"

 - name: import /N on compute nodes
   lineinfile:
     dest: /etc/fstab
     line:  "{{ headnode_private_ip }}:/N  /N  nfs  defaults 0 0"
     state: present
   tags:
     - export_home
   when: submit_host == "no"

 - name: mount -a on compute nodes
   command: "mount -a"
   tags:
     - export_home
   when: submit_host == "no"

# - name: disable firewalld so reboots don't break the cluster
#   service:
#     name: firewalld
#     enabled: False

# - name: configure tinyproxy on head node
#   template: src=tinyproxy.conf.j2 dest=/etc/tinyproxy/tinyproxy.conf
#   when: submit_host == "yes"

# - name: start tinyproxy
#   service: name=tinyproxy state=restarted enabled=yes
#   when: submit_host == "yes"

